# Generated by Django 3.1.14 on 2022-03-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0089_auto_20220310_0616'),
        ('terminal', '0047_auto_20220302_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='terminals', to='assets.Domain', verbose_name='Domain'),
        ),
    ]
