# Generated by Django 3.1.14 on 2022-04-01 03:32

from django.db import migrations, models


def initial_default_protocol(apps, schema_editor):
    Protocol = apps.get_model("terminal", "Protocol")
    Protocol.initial_to_db()


def migrate_terminal_protocols_field(apps, schema_editor):
    Terminal = apps.get_model("terminal", "Terminal")
    for t in Terminal.objects.all():
        t.reset_protocols_to_default()


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0048_terminal_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('http', 'HTTP'), ('ssh', 'SSH'), ('rdp', 'RDP'), ('mysql', 'MySQL'), ('oracle', 'Oracle'), ('mariadb', 'MariaDB'), ('postgresql', 'PostgreSQL'), ('sqlserver', 'SQLServer'), ('redis', 'Redis'), ('mongodb', 'MongoDB')], max_length=64, verbose_name='Name')),
                ('port', models.IntegerField(verbose_name='Port')),
            ],
        ),
        migrations.RunPython(initial_default_protocol),
        migrations.AddField(
            model_name='terminal',
            name='protocols',
            field=models.ManyToManyField(related_name='terminals', to='terminal.Protocol', verbose_name='Protocol'),
        ),
        migrations.RunPython(migrate_terminal_protocols_field)
    ]
