# Generated by Django 3.1.14 on 2022-04-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0050_auto_20220401_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='builtin',
            field=models.BooleanField(default=False, verbose_name='Builtin'),
        ),
        migrations.AlterUniqueTogether(
            name='protocol',
            unique_together={('name', 'port')},
        ),
    ]
